### ISSUE TITLE
Connection in use error

### ISSUE THREAD

**Issue by dignissimus** [cactool/cactool#76]
> I cannot run cactool either. I’m using a Mac Monterey with python 3.8. After pip installed, I try to run cactool via terminal and then I get the error Connection in use: ('', 8000). No webpage pops up...

_Originally posted by @polisci-quant-nerd in https://github.com/cactool/cactool/issues/75#issuecomment-1082018935_

**Comment by polisci-quant-nerd** [comment]
Hi, I think I figured out why there's a connection error. It's probably due to the fact that I forgot to kill the port I used for the previous connenction attempt. If I kill the Gunicorn port, I can connect. But still the no automatic webpage popping up, I have to copy paste the server address (http://0.0.0.0:8000/) to chrome to open the platform.

**Comment by dignissimus** [comment]
Thanks for the update.

I've updated the CLI so if you need to change the port you can, for example, run `cactool set port 8081`
